### ISSUE TITLE
Supermicro - SSE-7132S Switch - Error opening interface Eth0

### ISSUE THREAD

**Issue by ShivaniHIR** [microsoft/AzureStackHCI-Network-Switch-Validation#29]
Environment data (Device tested, inputs): 
DUT: SSE-7132S using sonic software version 3.1.0.13 , LLDP neighbouship and 10 VLANs setup on DUT and LLDP enabled on host device. 

LLDP packets from both sides are available as observed in wireshark capture. 

Output from tool (Attached)
[Result.log](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/11325789/Result.log)

**Comment by bkablawi** [comment]
Hello, based on the log, it seems the wrong adapter port has been input, and therefore no package is being detected. Please review adapter port input and try again.

**Comment by ShivaniHIR** [comment]
I am using Windows Server 2019 and ifIndex of the e1 interface.

**Comment by bkablawi** [comment]
Hello,

Is the ifIndex of the e1 interface being obtained from running Get-NetAdapter on the switch being tested? Ensure that the network adapter is the one you intend to use for testing. Below is an example from our test environment where we are using pnic01, which would mean we utilize ifIndex 5.

![image](https://user-images.githubusercontent.com/110482823/235487078-bbb21bee-e0ed-48a9-a1f6-9e0bdcc80185.png)

**Comment by ShivaniHIR** [comment]
Hi, 
We are still facing errors, and I have emailed you with the details. Thank you.

**Comment by bkablawi** [comment]
Interface open is now functional. Closing issue.
