### ISSUE TITLE
10 VLANs validation

### ISSUE THREAD

**Issue by luis-mora-hpeprod** [microsoft/AzureStackHCI-Network-Switch-Validation#30]
For results in Fail.zip, vlan validation is failing when parsed values match the input

- Detect: [710 711 712 713 714 715 716 717 718 719], but Input: [710 711 712 713 714 715 716 717 718 719]'

 
For results in False_Pass.zip all tests are passing but the values sent by the device are not matching the input values

- https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/blob/release/src/featureVLAN.go#L48
- This should return true for the TC to fail, instead, it returns false and VLANReportType.FeaturePass = PASS

[Fail.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/11325888/Fail.zip)
[False_Pass.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/11325889/False_Pass.zip)

**Comment by bkablawi** [comment]
Hello! Please refer to the latest release of the tool and try to test the switches again: https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/releases

This version addressed the VLAN issue.

**Comment by luis-mora-hpeprod** [comment]
Closed
