### ISSUE TITLE
NVIDIA - SN2000/3000/4000 - 23H2

### ISSUE THREAD

**Issue by berkink-nvidia-com** [microsoft/AzureStackHCI-Network-Switch-Validation#38]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website):
>NVIDIA

- Device series:
> [SN2000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn2000/) (10, 25, 100 GbE)
> [SN3000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn3000/) (10, 25, 100 GbE)
> [SN4000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn4000/) (10, 25, 100, 400 GbE)

- Speeds supported (GbE):
> [SN2000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn2000/) (10, 25, 100 GbE)
> [SN3000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn3000/) (10, 25, 100 GbE)
> [SN4000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn4000/) (10, 25, 100, 400 GbE)

- Minimum firmware version requirement:
> Cumulus Linux 5.1 or later

- Link to device datasheet: 
> [SN2000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn2000/) (10, 25, 100 GbE)
> [SN3000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn3000/) (10, 25, 100 GbE)
> [SN4000](https://www.nvidia.com/en-us/networking/ethernet-switching/spectrum-sn4000/) (10, 25, 100, 400 GbE)

## After the tool execution successfully, there will be five files:

PDF File -> Yes
JSON File -> No
YAML File -> No
Log File -> No
PCAP file -> Yes

Please attach these here and submit for review!
[Nvidia_Cumulus_AzureHCI_Validations.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12193349/Nvidia_Cumulus_AzureHCI_Validations.zip)

**Comment by berkink-nvidia-com** [comment]
[Nvidia_Cumulus_AzureHCI_Validations_07302023.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12208625/Nvidia_Cumulus_AzureHCI_Validations_07302023.zip)

Hello, repeated all the tests and gathered data including all essential output files. Please check.

PDF File -> Yes
JSON File -> No
YAML File -> Yes
Log File -> Yes
PCAP file -> Yes

**Comment by bkablawi** [comment]
Results validated. Closing.
