### ISSUE TITLE
[Cisco] - [N9K-C93180YC-FX] - 23H2

### ISSUE THREAD

**Issue by robinmathews2023** [microsoft/AzureStackHCI-Network-Switch-Validation#39]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): Cisco 

- Device series: Nexus 93180YC-FX

- Speeds supported (GbE): 48 10/25-Gigabit + 6 40/100-Gigabit

- Minimum firmware version requirement:  16.0(3)

[Result_pciPassthru0.pdf](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12196622/Result_pciPassthru0.pdf)
[result.log](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12196623/result.log)

- Link to device datasheet: https://www.cisco.com/c/en/us/td/docs/switches/datacenter/nexus9000/hw/n93180ycfx_hig/guide/b_n93180ycFX_nxos_hardware_installation_guide/b_n93180ycFX_nxos_hardware_installation_guide_chapter_01010.html

## After the tool execution successfully, there will be five files:

PDF File
JSON File
[Archive.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12196643/Archive.zip)

YAML File
Log File
PCAP file

Please attach these here and submit for review!

**Comment by robinmathews2023** [comment]
Adding new results  with Cisco ACI 6.0(3d) Release . We dont  have a full pass for storage . We would like to list our switches for compute, SDN and management roles only for now .Please do the needful.
[AZURE-603d-PASS.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12315991/AZURE-603d-PASS.zip)
[Result_Ethernet1.pdf](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12316000/Result_Ethernet1.pdf)

**Comment by robinmathews2023** [comment]
Here is the full pass results with the latest build 603e.Please review .

[Azure-HCI-Cert-All-Pass.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12362411/Azure-HCI-Cert-All-Pass.zip)
[Result_Ethernet1.pdf](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12362416/Result_Ethernet1.pdf)

**Comment by robinmathews2023** [comment]
[Azure603EFullPass.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12402831/Azure603EFullPass.zip)
603E full pass results

**Comment by bkablawi** [comment]
Confirmed results, ACI OS posted.
