### ISSUE TITLE
[Cisco] - [9332D-H2R] - 23H2

### ISSUE THREAD

**Issue by ger-sheehan** [microsoft/AzureStackHCI-Network-Switch-Validation#40]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): Cisco

- Device series: 9332D-H2R

- Speeds supported (GbE): (100, 400 GbE)

- Minimum firmware version requirement: NX-OS 10.4(1)

- Link to device datasheet: 

## After the tool execution successfully, there will be four files:

[N9K-C9332D-H2R.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/12411687/N9K-C9332D-H2R.zip)

PDF File
YAML File
Log File
PCAP file

Please attach these here and submit for review!

**Comment by bkablawi** [comment]
Approved and listed
