### ISSUE TITLE
NETGEAR -M4500 Series - 23H2

### ISSUE THREAD

**Issue by Apendleton52** [microsoft/AzureStackHCI-Network-Switch-Validation#42]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

@NETGEAR for Twitter / X and LinkedIn posts.

- Organization (As you want it to appear on the website): NETGEAR

- Device series: M4500 Series

- Speeds supported (GbE): 1GbE, 10GbE, 25GbE, 40GbE, 50GbE, 100GbE

- Minimum firmware version requirement: 7.0.3.9

- Link to device datasheet:  https://www.netgear.com/assets/campaign/121401/images/m4500.pdf

## After the tool execution successfully, there will be four files:

PDF File
YAML File
Log File
PCAP file

Please attach these here and submit for review!
[all the files.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/13626377/all.the.files.zip)

**Comment by bkablawi** [comment]
Submission approved
