### ISSUE TITLE
Cisco - 93400LD-H1 - 22H2/23H2

### ISSUE THREAD

**Issue by ger-sheehan** [microsoft/AzureStackHCI-Network-Switch-Validation#43]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): Cisco Systems

- Device series: 9300-H1

- Speeds supported (GbE): 10G, 25G, 50G

- Minimum firmware version requirement: NX-OS 10.4(2)

- Link to device datasheet: https://www.cisco.com/c/en/us/products/collateral/switches/nexus-9000-series-switches/nb-06-nexus-93400ld-h1-switch-ds-cte-en.html

## After the tool execution successfully, there will be four files:

PDF File
YAML File
Log File
PCAP file
[93400LD-H1.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/13716413/93400LD-H1.zip)

Please zip and upload these here to submit for review!

**Comment by bkablawi** [comment]
Submission approved.
