### ISSUE TITLE
HPE - HPE Networking Comware Switch Series 5944 - 22H2/23H2

### ISSUE THREAD

**Issue by RAVI-SHARMA-HPE** [microsoft/AzureStackHCI-Network-Switch-Validation#45]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): HPE Aruba Networking

- Device series: HPE Networking Comware Switch Series 5944

- Speeds supported (GbE): -  48 x 1/10 GbE Base-T ports and 6 x 40 or 100 GbE QSFP28
-- Minimum firmware version requirement: Comware 7 version R6710 or later

- Link to device datasheet:  https://www.hpe.com/psnow/doc/a50002580enw.pdf?jumpid=in_pdfviewer-psnow

## After the tool execution successfully, there will be four files:

PDF File - uploaded
YAML File - uploaded 
Log File - uploaded
PCAP file - uploaded 
[5944 Result.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/13807775/5944.Result.zip)

**Comment by bkablawi** [comment]
Submission approved.
