### ISSUE TITLE
Arista - 7000 series - 22H2/23H2

### ISSUE THREAD

**Issue by meghasinha90** [microsoft/AzureStackHCI-Network-Switch-Validation#50]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): Arista Networks

- Device series: 
7050X3
7060X
7260X3
7060X4
7280R3

- Speeds supported (GbE):
7050X3 (10, 25, 100, 400 GbE)
7060X (10, 25, 100 GbE)
7260X3 (10, 25, 100 GbE)
7060X4 (10, 25, 100, 400 GbE)
7280R3 (10, 25, 100, 400 GbE)

- Minimum firmware version requirement: EOS 4.30.0F and later

- Link to device datasheet: 
https://www.arista.com/assets/data/pdf/Datasheets/7050X3-Datasheet.pdf
https://www.arista.com/assets/data/pdf/Datasheets/7060X_7260X_DS.pdf
https://www.arista.com/assets/data/pdf/Datasheets/7260X3_Datasheet.pdf
https://www.arista.com/assets/data/pdf/Datasheets/7060X4-Datasheet.pdf
https://www.arista.com/assets/data/pdf/Datasheets/7280R3-Data-Sheet.pdf

## After the tool execution successfully, there will 
[Arista_Report_01152024.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/13943006/Arista_Report_01152024.zip)
be four files:

PDF File
YAML File
Log File
PCAP file

Please zip and upload these here to submit for review!

**Comment by bkablawi** [comment]
Submission accepted.
