### ISSUE TITLE
Dell - S52xx - 22H2/23H2

### ISSUE THREAD

**Issue by ManasDell** [microsoft/AzureStackHCI-Network-Switch-Validation#52]
[result.log](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/15483216/result.log)
[Result_SLOT 8 Port 2.pdf](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/15483217/Result_SLOT.8.Port.2.pdf)
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): Dell

- Device series: S52xx

- Speeds supported (GbE): 10G, 25G, 100G

- Minimum firmware version requirement:

- Link to device datasheet: https://www.delltechnologies.com/asset/en-us/products/networking/technical-support/dell_emc_networking-s5200_on_spec_sheet.pdf

## After the tool execution successfully, there will be four files:

PDF File
YAML File
Log File
PCAP file

Please zip and upload these here to submit for review!
[Dell Switch_Azure Stack HCI 23H2.zip](https://github.com/microsoft/AzureStackHCI-Network-Switch-Validation/files/15483278/Dell.Switch_Azure.Stack.HCI.23H2.zip)

**Comment by liunick-msft** [comment]
Submission accepted.
