### ISSUE TITLE
Error while running test - Supermicro 

### ISSUE THREAD

**Issue by ShivaniHIR** [microsoft/AzureStackHCI-Network-Switch-Validation#53]
Environment data: 
 Device tested : SSE-C4632 
Inputs: Interface Index
Test version: SwitchValidationTool_2024.04.09_53  
 
Output from tool : 
![image](https://github.com/user-attachments/assets/072afcbf-f736-4880-9532-0a076fd9be9d)

Issue: 
Test does not create PDF and YML.

**Comment by liunick-msft** [comment]
Hi @ShivaniHIR, can you please provide this information:
- Are you in the administrator mode of terminal?
- The command you execute in the terminal.
- The output of "Get-NetAdapter" if possible.

In the meantime, if Wireshark is installed on this test host, can you check if Wireshark can capture the same traffic? If yes, can you provide the output file of the same NIC?
Thanks!

**Comment by ShivaniHIR** [comment]
Thank you for your support @liunick-msft
