### ISSUE TITLE
[Supermicro] - [C4632] - 22H2/23H2

### ISSUE THREAD

**Issue by ShivaniHIR** [microsoft/AzureStackHCI-Network-Switch-Validation#54]
- Organization (As you want it to appear on the website): SuperMicro

- Device series:  SSE-C4632

- Speeds supported (GbE): 10, 25, 40, 50, 100GbE 

- Minimum firmware version requirement: Broadcom Advanced Enterprise SONiC OS 4.2.1

- Link to device datasheet: https://www.supermicro.com/datasheet/datasheet_SSE-C4632.pdf 

## After the tool execution successfully, there will be five files:

- PDF File - Yes
- YAML File - Yes
- Log File - Yes
- PCAP file - Yes

Please zip and upload these here to submit for review!
[Supermicro_Sonic_AzureHCI.zip](https://github.com/user-attachments/files/16503054/Supermicro_Sonic_AzureHCI.zip)

**Comment by bkablawi** [comment]
Submission approved
