### ISSUE TITLE
[Supermicro] - [T8032] - 22H2/23H2

### ISSUE THREAD

**Issue by ShivaniHIR** [microsoft/AzureStackHCI-Network-Switch-Validation#56]
- Organization (As you want it to appear on the website): SuperMicro

- Device series: SSE-T8032

- Speeds supported (GbE): 10, 25, 40, 50, 100, 200 & 400

- Minimum firmware version requirement: Broadcom Advanced Enterprise SONiC OS 4.2.1

- Link to device datasheet: https://www.supermicro.com/datasheet/datasheet_SSE-T8032S.pdf 

## After the tool execution successfully, there will be five files:

- PDF File - Yes
- YAML File - Yes
- Log File - Yes
- PCAP file - Yes

Please zip and upload these here to submit for review!

[Supermicro_Sonic_AzureHCI_T8032.zip](https://github.com/user-attachments/files/16784070/Supermicro_Sonic_AzureHCI_T8032.zip)

**Comment by bkablawi** [comment]
Submission accepted
