### ISSUE TITLE
[Juniper] - [QFX5120] - 22H2/23H2

### ISSUE THREAD

**Issue by MissNicoleHenry** [microsoft/AzureStackHCI-Network-Switch-Validation#57]
*Ensure you are utilizing the latest version of the tool from the release page*

## Please fill in the following:

- Organization (As you want it to appear on the website): Juniper Networks

- Device series: QFX5120 series

- Speeds supported (GbE): 10, 25, 40, 100

- Minimum firmware version requirement: 23.4R2.13

- Link to device datasheet: https://www.juniper.net/content/dam/www/assets/datasheets/us/en/switches/qfx5120-ethernet-switch-datasheet.pdf

## After the tool execution successfully, there will be five files:

- PDF File
- YAML File
- Log File
- PCAP file
- Switch Configurations (Please Remove Sensitive Data!)

Please zip and upload these here to submit for review!
[QFX5120_Series.zip](https://github.com/user-attachments/files/17251083/QFX5120_Series.zip)

**Comment by bkablawi** [comment]
Submission approved

**Comment by bkablawi** [comment]
#sign-off
